# Generated by Django 4.2.6 on 2023-10-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0002_clients_departments_expense_orders_planner_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
