# Generated by Django 4.2.6 on 2023-10-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0004_brands_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brands',
            name='image',
        ),
    ]
