# Generated by Django 4.2.6 on 2023-10-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0006_brands_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/'),
        ),
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='supplier_photos/'),
        ),
    ]
