# Generated by Django 4.2.6 on 2023-10-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0007_clients_photo_products_photo_staff_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='products',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='photo',
        ),
    ]
