# Generated by Django 4.2.6 on 2023-10-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0008_remove_clients_photo_remove_products_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/'),
        ),
    ]
