# Generated by Django 4.2.6 on 2023-10-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0012_remove_products_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='anbarprogram.brands'),
            preserve_default=False,
        ),
    ]
