# Generated by Django 4.2.6 on 2023-10-25 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0013_products_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='anbarprogram.clients'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='anbarprogram.brands'),
        ),
    ]
