# Generated by Django 4.2.6 on 2023-10-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0016_planner_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='anbarprogram.departments'),
            preserve_default=False,
        ),
    ]
