# Generated by Django 4.2.6 on 2023-10-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0019_staff_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='purchase',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.FloatField(max_length=20),
        ),
    ]
