# Generated by Django 4.2.6 on 2023-10-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0022_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='accept',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
