# Generated by Django 4.2.6 on 2023-10-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0023_orders_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='accept',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
