# Generated by Django 4.2.6 on 2023-11-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0025_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
