# Generated by Django 4.2.6 on 2023-11-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0030_expense_user_id_positions_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='planner',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
