# Generated by Django 4.2.6 on 2023-11-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0039_remove_customuser_confirm_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
