# Generated by Django 4.2.6 on 2023-11-16 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0043_customuser_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTablePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(choices=[('Brands', 'Brands'), ('Clients', 'Clients'), ('Departments', 'Departments'), ('Expense', 'Expense'), ('Orders', 'Orders'), ('Planner', 'Planner'), ('Positions', 'Positions'), ('Products', 'Products'), ('Staff', 'Staff'), ('Suppliers', 'Suppliers'), ('CustomUser', 'CustomUser')], max_length=255)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'table_name')},
            },
        ),
    ]
