# Generated by Django 4.2.6 on 2023-11-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0044_usertablepermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTablePermissions',
        ),
    ]
