# Generated by Django 4.2.6 on 2023-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0045_delete_usertablepermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
            ],
        ),
    ]
