# Generated by Django 4.2.6 on 2023-11-18 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0047_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='perms',
            name='item_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
