# Generated by Django 4.2.6 on 2023-11-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0048_perms_item_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perms',
            name='item_value',
        ),
    ]
