# Generated by Django 4.2.6 on 2023-11-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0049_remove_perms_item_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='perms',
            name='item_value',
            field=models.IntegerField(default=0),
        ),
    ]
