# Generated by Django 4.2.6 on 2023-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0053_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perms',
            name='item_value',
            field=models.BooleanField(default=0),
        ),
    ]
