# Generated by Django 4.2.6 on 2023-11-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0054_alter_perms_item_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='accept',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
