# Generated by Django 4.2.6 on 2023-11-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0056_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='tarix',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='qebul',
            new_name='recive',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='gonderen',
            new_name='send',
        ),
    ]
