# Generated by Django 4.2.6 on 2023-12-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anbarprogram', '0058_rename_recive_chat_receive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='table',
            new_name='name',
        ),
    ]
